#!/bin/bash

psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<-EOSQL
CREATE INDEX idx_${TABLE_NAME}_watertype ON $TABLE_NAME ($WATER_TYPE_COLUMN_NAME);
CREATE INDEX idx_${TABLE_NAME}_shape ON $TABLE_NAME USING GIST ($GEOMETRY_COLUMN_NAME);
EOSQL
